### ISSUE TITLE
Request for Detailed Instructions on Output Shape Definition

### ISSUE THREAD

**Issue by vantienpham** [inspiros/tvdcn#5]
Hello,

Firstly, I would like to express my appreciation for your outstanding repository.

After scanning the repository, I couldn't locate detailed instructions on how to define the output shape.
In my opinion, it would greatly benefit users if there were clear instructions explaining the relationship between the input and output shapes, similar to torch's conv2d.
![image](https://github.com/inspiros/tvdcn/assets/25927039/1909b2f6-92b4-413b-8b1f-feea89df6562)

To illustrate my point, I would like to bring up an issue I encountered while applying the `PackedDeformConvTranspose2d` to resnet56. In cases where `stride=2`, the output shape appears to be peculiar. Here's a MWE:
```
>>> x = torch.rand(16, 3, 32, 32)
>>> conv = nn.Conv2d(3, 5, kernel_size=3, stride=2, padding=1, bias=False)
>>> tdconv = PackedDeformConvTranspose2d(3, 5, kernel_size=3, stride=2, padding=1, bias=False, modulated=True)
>>> conv(x).shape
torch.Size([16, 5, 16, 16])
>>> tdconv(x).shape
torch.Size([16, 5, 63, 63])
```
As seen from the MWE, the output shape of tvdcn and conv2d differs. Could you please clarify if this difference is expected? If so, I would greatly appreciate guidance on how to specify the parameters to ensure that the output shape of tvdcn remains consistent with conv2d in this particular case.

Many thanks in advance!

**Comment by inspiros** [comment]
Deformable convolution shares the same formula to compute output shapes with conventional convolution.
```math
out = \left\lfloor\frac{in + 2 \times pad - (dilation \times (kernel\_size - 1) + 1)}{stride}\right\rfloor + 1
```

Likewise, **transposed** deformable convolution shares the same formula to compute output shapes with conventional **transposed** convolution.
```math
out = (in - 1) \times stride - 2 \times pad + dilation \times (kernel\_size - 1) + 1 + out\_pad
```

The problem in your MWE is that you are comparing the output of conventional convolution with the output of **transposed** deformable convolution. Instead, try this:
```python
import torch
import tvdcn

x = torch.rand(16, 3, 32, 32)
conv = torch.nn.Conv2d(3, 5, kernel_size=3, stride=2, padding=1, bias=False)
dconv = tvdcn.PackedDeformConv2d(3, 5, kernel_size=3, stride=2, padding=1, bias=False, modulated=True)
assert conv(x).shape == dconv(x).shape  # torch.Size([16, 5, 16, 16])

conv = torch.nn.ConvTranspose2d(3, 5, kernel_size=3, stride=2, padding=1, bias=False)
dconv = tvdcn.PackedDeformConvTranspose2d(3, 5, kernel_size=3, stride=2, padding=1, bias=False, modulated=True)
assert conv(x).shape == dconv(x).shape  # torch.Size([16, 5, 63, 63])
```

Anw, thanks for your suggestion, maybe I will add these equations somewhere in the readme.

**Comment by vantienpham** [comment]
Thanks for your explanation.
So it's impossible to decrease the output shape with transposed convolution since this is an upsampling process.
In my case for resnet56/cifar, I decided to keep the conventional Conv2d in the case of `stride=2` (otherwise, replacing it with tvdcn) as a technical solution.
Btw, a performance boost on cifar isn't expected since the plane size is too small for deformable convs, but just a test.

**Comment by inspiros** [comment]
Yes. That's why transposed deformable convolution should be evaluated on tasks such as segmentation or generation.
