### ISSUE TITLE
Segmentation error

### ISSUE THREAD

**Issue by vantienpham** [inspiros/tvdcn#6]
Hi, thank you for the work.
I've met the segmentation error from d2f6e71e5898fd62399fc37929d23683a0054b0f.
I tried 2 methods of building from source: `python setup.py develop` and `python setup.py build_ext --inplace; python setup.py bdist_wheel; pip install dist/*.whl`
```bash
>>> import tvdcn
tvdcn.>>> tvdcn.__version__
'0.4.0'
>>> tvdcn.has_ops()
True
>>> tvdcn.with_cuda()
True
>>>
(base) van-tien.pham@siim-3:~/tvdcn/tests$ python test_grad.py
DeformConvTestArgs(spatial_dim=2
- conv_params:
        in_channels     = 4
        out_channels    = 2
        kernel_size     = (2, 3)
        stride          = (1, 2)
        padding         = (0, 1)
        dilation        = (1, 2)
        weight_groups   = 1
        offset_groups   = 2
        mask_groups     = 1
        transposed      = False
- input_params:
        batch_size      = 1
        in_size         = (5, 6)
        out_size        = [4, 2]
- input_shapes:
        input           = torch.Size([1, 4, 5, 6])
        weight          = torch.Size([2, 4, 2, 3])
        offset          = torch.Size([1, 24, 4, 2])
        mask            = torch.Size([1, 6, 4, 2])
        bias            = torch.Size([2])
- output_shapes:
        expected_cols   = torch.Size([4, 12])
        expected_output = torch.Size([1, 2, 4, 3])
- factory_params:
        device          = cuda
        dtype           = torch.float64
        contiguous      = True
)
Erreur de segmentation
```
This also happens with ecn.
I'm not sure if this is just because of my machine/installation. Can you please verify?
During building, I notice that at some moments the process consumes 100% CPU, which didn't happen with the previous version.
Thanks in advance for your help!

**Comment by inspiros** [comment]
Fixed with f1872bdc9114d12093131994f4dc2e12600ba207.

Regarding the high CPU consumption, it is because I enabled [ninja-build](https://ninja-build.org/) as it helps saving a lot of time. It used to be disabled because `torch.utils.cpp_extension.BuildExtension` caused an error on Windows in earlier versions of `torch`. They seem to have sorted that out but I didn't notice until recently. You can disable ninja by modifying the `setup.py` before compiling with:
```python
def setup_package():
    setup(
        version=get_version(),
        ext_modules=get_extensions(),
        cmdclass={
            'build_ext': torch.utils.cpp_extension.BuildExtension.with_options(use_ninja=False)
        },
    )
```
